#!/usr/bin/python#
import base64

file_name = '/home/lxy/GitHub/EC601-Project1/images/15.jpg'
with open(file_name, 'r') as image:
    image_content = image.read()
    encoded_content = base64.b64encode(image_content)
    print (encoded_content)
