#!/usr/bin/python#
import base64
import wget

wget.download('http://www.personal.psu.edu/users//w/z/wzz5072/mini.jpg', '/home/lxy/GitHub/EC601-Project1/images/')

file_name = '/home/lxy/GitHub/EC601-Project1/images/mini.jpg'
with open(file_name, 'r') as image:
    image_content = image.read()
    encoded_content = base64.b64encode(image_content)
    print (encoded_content)
