#!/usr/bin/python#
import base64
import wget
from PIL import Image

from google.cloud import vision_v1

client = vision_v1.ImageAnnotatorClient()

file_name = '/home/lxy/GitHub/EC601-Project1/images/mini.jpg'
with open(file_name, 'rb') as image:
    image_content = image.read()
    encoded_content = base64.b64encode(image_content)
    #print (encoded_content)

requests=[
        {
            "image":{
                "content": encoded_content
                },
            "features":[
                {
                    "type":"FACE_DETECTION",
                    "maxResults":10
                    }
                ]
            }
        ]

#request =  {'image': {'content': encoded_content},}
response = client.annotate_image(requests)
print(response)
        
